[WIP] Add v1 API and internal conversions with v1beta1
openshift/cluster-kube-descheduler-operator pull request #178
Opened 2021-03-30 18:08 UTC by damemi

2021-03-30 18:10 UTC, damemi reviewed
/cc @soltysh @ingvagabund 
I think I've added the internal API correctly (but running the generate script locally will depend on https://github.com/kubernetes/kubernetes/pull/100666)

Next step is adding the code to actually consume/convert whatever version is passed as a CRD. This will let us bridge existing stored v1beta1 versions to the new v1 version without the extra fields

2021-04-05 21:01 UTC, damemi commented
At this point it runs properly for me, but the CRD schema gen needs work to patch it. I just generated this with `controller-gen` manually from the latest upstream branch (rather than our makefile targets, which is fine since we don't need to just patch the openapi schema)

2021-04-07 07:47 UTC, ingvagabund requested changes
Just nits

2021-04-07 07:47 UTC, ingvagabund commented on pkg/operator/target_config_reconciler.go
> +	deschedulerv1 "github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1"
nit: move this next to other `github.com/openshift/cluster-kube-descheduler-operator` imports

2021-04-07 07:47 UTC, ingvagabund commented on pkg/apis/descheduler/v1/doc.go
> -// +k8s:conversion-gen=github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler
This was added in the first commit. Can you remove it there instead?

2021-04-07 07:47 UTC, ingvagabund commented on pkg/apis/descheduler/v1beta1/doc.go
> -// +k8s:conversion-gen=github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler
This was added in the first commit. Can you remove it there instead?

2021-04-07 17:06 UTC, damemi commented
Thanks @ingvagabund, I reorganized some of the commits and removed the Makefile changes since those are broken.

So right now, this can't generate a new CRD if there are any changes. I don't think that is technically a blocker, since we have the ability to manually generate any CRD changes should they come up. But it is definitely an issue that could warrant its own bugzilla. @soltysh what do you think about this?

2021-04-07 18:38 UTC, soltysh approved these changes
/lgtm

2021-04-07 18:39 UTC, merged