[WIP] Add Profiles to evict localStorage pods/ignore PVC pods
openshift/cluster-kube-descheduler-operator pull request #198
Opened 2021-06-08 19:00 UTC by damemi

Adds profiles which will enable these options in the descheduler policy
ref: https://issues.redhat.com/browse/WRKLDS-304

2021-08-03 19:50 UTC, damemi reviewed
/cc @ingvagabund @kasturinarra

2021-08-04 11:38 UTC, ingvagabund approved these changes

2021-08-04 11:38 UTC, ingvagabund commented on manifests/4.9/kube-descheduler-operator.crd.yaml
> +                  type: string
duplicated line

2021-08-04 11:38 UTC, ingvagabund commented on manifests/4.9/kube-descheduler-operator.crd.yaml
> +                type: array
duplicated line

2021-08-04 11:38 UTC, ingvagabund commented on bindata/assets/profiles/EvictPodsWithLocalStorage.yaml
> +evictLocalStoragePods: true
From https://github.com/openshift/cluster-kube-descheduler-operator/blob/c9a04369033fb1b4476d6577b60511f6cf25a866/pkg/operator/target_config_reconciler.go#L238:
```
// Merge will fill any empty for value type attributes on the dst struct using corresponding
// src attributes if they themselves are not empty. dst and src must be valid same-type structs
// and dst must be a pointer to struct.
// It won't merge unexported (private) fields and will do recursively any exported field.
func Merge(dst, src interface{}, opts ...func(*Config)) error {
	return merge(dst, src, opts...)
}
```

empty fields (i.e. ignorePvcPods and evictLocalStoragePods set to false) will get set to true if set through the profiles. Looks good.

2021-08-04 11:39 UTC, ingvagabund requested changes
Removing the duplicated lines is the only nit

2021-08-09 14:26 UTC, ingvagabund commented
/lgtm

2021-08-09 15:21 UTC, merged