update for 4.12 and MULTIARCH-2635
openshift/cluster-kube-descheduler-operator pull request #270
Opened 2022-08-23 12:58 UTC by chandra0007

Addresses MULTIARCH-2635 Make OLM Label for Descheduler Policy for v4.12.0
Adds S390, ppc, and arm support to operator hub.

Signed-off-by: Chandrasekhar Bade <cbade@redhat.com>

2022-08-23 13:04 UTC, prb112 commented
Reached out to @manojnkumar @jaypoulz in Slack to review on behalf of multiarch

2022-08-24 15:41 UTC, manojnkumar commented
/LGTM for master
Needs to be back-ported to the release-4.12 branch as well?

2022-08-25 15:46 UTC, jaypoulz commented
IMHO, we should decouple the 4.11 -> 4.12 changes from the changes to the OLM flags. Let me see if I can find the owner of this operator to ensure we get feedback / set this up according to their plan.

**Update**: Please ignore this and proceed with the changes as recommended by the maintainers. 👍

2022-08-25 16:28 UTC, ingvagabund requested changes

2022-08-25 16:28 UTC, ingvagabund commented on manifests/4.12/cluster-kube-descheduler-operator.v4.12.0.clusterserviceversion.yaml
> +    olm.skipRange: ">=4.8.0 <4.12.0"
4.8.0 -> 4.9.0

2022-08-25 16:28 UTC, ingvagabund commented on manifests/4.12/cluster-kube-descheduler-operator.v4.12.0.clusterserviceversion.yaml
>    minKubeVersion: 1.24.0
1.24.0 -> 1.25.0

2022-08-25 16:29 UTC, ingvagabund commented
If you could also please update https://github.com/openshift/cluster-kube-descheduler-operator/blob/master/manifests/art.yaml#L10-L11 to:
```
    - search: 'olm.skipRange: ">=4.9.0 <{MAJOR}.{MINOR}.0"'
      replace: 'olm.skipRange: ">=4.9.0 <{FULL_VER}"'
```

2022-08-25 16:37 UTC, jaypoulz commented
/hold

Adding a hold flag to ensure we can control when it gets merged post updates and approval.

2022-08-26 13:16 UTC, chandra0007 commented on manifests/4.12/cluster-kube-descheduler-operator.v4.12.0.clusterserviceversion.yaml
> +    olm.skipRange: ">=4.8.0 <4.12.0"
Updated per review

2022-08-26 22:14 UTC, manojnkumar commented
/LGTM

2022-08-29 17:35 UTC, ingvagabund commented
@chandra0007 would you please squash the commits before the final approval?

2022-08-30 15:16 UTC, ingvagabund commented
/approve
/lgtm

2022-08-30 15:35 UTC, chandra0007 commented
/unhold

2022-08-30 18:08 UTC, merged